workflows:
  maui-ios-adhoc:
    name: MAUI iOS AdHoc Build - .NET 9
    environment:
      xcode: 16.3
      cocoapods: default
      vars:
        BUNDLE_ID: com.worldsystem.wsinvmovil
        DEVELOPMENT_TEAM: 64P2Z9G4SL
      ios_signing:
        certificates:
          - distribute_certificate_p12
        provisioning_profiles:
          - Wsinvmovil-AdhocProfile

    scripts:
      - name: Instalar .NET 9 SDK
        script: |
          curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version 9.0.203 --install-dir $HOME/dotnet
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$HOME/dotnet:$PATH
          dotnet --info

      - name: Restaurar dependencias y workloads
        script: |
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$HOME/dotnet:$PATH
          dotnet workload restore
          dotnet restore Wsinvmovil/Wsinvmovil.csproj

      - name: Aplicar perfiles de firma
        script: |
          xcode-project use-profiles

      - name: Compilar IPA AdHoc
        script: |
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$HOME/dotnet:$PATH
          dotnet publish Wsinvmovil/Wsinvmovil.csproj \
            -f:net9.0-ios \
            -c:Release \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:CodesignKey="Apple Distribution" \
            -p:CodesignProvision="Wsinvmovil-AdhocProfile" \
            -p:ApplicationId=${BUNDLE_ID} \
            -p:CodesignTeamId=${DEVELOPMENT_TEAM}

    artifacts:
      - "Wsinvmovil/bin/Release/net9.0-ios/ios-arm64/publish/*.ipa"


