workflows:
  ios-maui-net9:
    name: MAUI iOS Build - .NET 9 via dotnet-install.sh
    environment:
      xcode: 16.3
      cocoapods: default
    scripts:
      - name: Install .NET SDK 9.0.203 via script
        script: |
          curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version 9.0.203 --install-dir $HOME/dotnet
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$HOME/dotnet:$PATH
          dotnet --info

      - name: Install MAUI workloads
        script: |
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$HOME/dotnet:$PATH
          dotnet workload restore
          dotnet restore Wsinvmovil/Wsinvmovil.csproj
          dotnet workload list
    

      - name: Restore NuGet packages
        script: |
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$HOME/dotnet:$PATH
          dotnet restore Wsinvmovil/Wsinvmovil.csproj

      - name: Build iOS .NET MAUI App for Simulator
        script: |
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$HOME/dotnet:$PATH
          dotnet build Wsinvmovil/Wsinvmovil.csproj \
            -c Release \
            -f:net9.0-ios \
            -p:RuntimeIdentifier=iossimulator-arm64
            -p:PlatformTarget=AnyCPU \
           -p:EnableWindowsTargeting=false
   
    artifacts:
      - '**/*.app'

